# -*- coding: utf-8 -*-
"""insert_to_postgres.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10FlxoHwQEJcMZh3qFGpmVPl_Qf4x9S0j
"""

import pandas as pd
from sqlalchemy import create_engine

# ✅ Load your scraped CSV file
df = pd.read_csv(r"C:\Users\hp\Desktop\samsung_phones.csv")  # change path if needed

# ✅ PostgreSQL connection details
USER = "postgres"
PASSWORD = "@@@@@"   # replace with your actual password
HOST = "localhost"
DBNAME = "samsungdb"

# ✅ Create connection string
engine = create_engine(f"postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}/{DBNAME}")

# ✅ Insert data into table
df.to_sql("samsung_phones", engine, if_exists="replace", index=False)

print("✅ Data inserted into PostgreSQL successfully!")
